# Generated by Django 5.2.11 on 2026-02-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(max_length=200, verbose_name="Имя победителя"),
                ),
                (
                    "victory_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата победы"),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(verbose_name="Кол-во рядов грида"),
                ),
            ],
            options={
                "verbose_name": "Победитель",
                "verbose_name_plural": "Победители",
                "ordering": ["row_count", "victory_date"],
            },
        ),
    ]
